# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - "C:/Windows/System32/LogFiles/Firewall/pfirewall_domain.log"
  exclude_lines: ['\s\bff02::.*?\s\bRECEIVE\b', '\s\b5353\b\s\b5353\b\s.*?\s\bRECEIVE\b', '\s\b(80|443)\b\s.*?\s\bSEND\b','\s\bDROP\b\s\b(TCP|UDP|ICMP)\b\s\b(10\.16\.1\.1|10\.16\.1\.128)\b\s.*?\s\bRECEIVE\b']
  encoding: utf8
  close_inactive: 1m
  ignore_older: 2m
  clean_inactive: 24h
  tags: ["filebeat-windows-firewall-domain"]
  processors:
    - drop_event.when.or:
      - regexp.message: '\s\bff02::.*?\s\bRECEIVE\b'
      - regexp.message: '\s\b5353\b\s\b5353\b\s.*?\s\bRECEIVE\b'
      - regexp.message: '\s\b(80|443)\b\s.*?\s\bSEND\b'
      - regexp.message: '\s\bDROP\b\s\b(TCP|UDP|ICMP)\b\s\b(10\.16\.1\.1|10\.16\.1\.128)\b\s.*?\s\bRECEIVE\b'
      
- type: log
  enabled: true
  paths:
    - "C:/Windows/System32/LogFiles/Firewall/pfirewall_private.log"
  exclude_lines: ['\s\bff02::.*?\s\bRECEIVE\b', '\s\b5353\b\s\b5353\b\s.*?\s\bRECEIVE\b', '\s\b(80|443)\b\s.*?\s\bSEND\b','\s\bDROP\b\s\b(TCP|UDP|ICMP)\b\s\b(10\.16\.1\.1|10\.16\.1\.128)\b\s.*?\s\bRECEIVE\b']
  encoding: utf8
  close_inactive: 1m
  ignore_older: 2m
  clean_inactive: 24h
  tags: ["filebeat-windows-firewall-private"]
  processors:
    - drop_event.when.or:
      - regexp.message: '\s\bff02::.*?\s\bRECEIVE\b'
      - regexp.message: '\s\b5353\b\s\b5353\b\s.*?\s\bRECEIVE\b'
      - regexp.message: '\s\b(80|443)\b\s.*?\s\bSEND\b'
      - regexp.message: '\s\bDROP\b\s\b(TCP|UDP|ICMP)\b\s\b(10\.16\.1\.1|10\.16\.1\.128)\b\s.*?\s\bRECEIVE\b'

- type: log
  enabled: true
  paths:
    - "C:/Windows/System32/LogFiles/Firewall/pfirewall_public.log"
  exclude_lines: ['\s\bff02::.*?\s\bRECEIVE\b', '\s\b5353\b\s\b5353\b\s.*?\s\bRECEIVE\b', '\s\b(80|443)\b\s.*?\s\bSEND\b','\s\bDROP\b\s\b(TCP|UDP|ICMP)\b\s\b(10\.16\.1\.1|10\.16\.1\.128)\b\s.*?\s\bRECEIVE\b']
  encoding: utf8
  close_inactive: 1m
  ignore_older: 2m
  clean_inactive: 24h
  tags: ["filebeat-windows-firewall-public"]
  processors:
    - drop_event.when.or:
      - regexp.message: '\s\bff02::.*?\s\bRECEIVE\b'
      - regexp.message: '\s\b5353\b\s\b5353\b\s.*?\s\bRECEIVE\b'
      - regexp.message: '\s\b(80|443)\b\s.*?\s\bSEND\b'
      - regexp.message: '\s\bDROP\b\s\b(TCP|UDP|ICMP)\b\s\b(10\.16\.1\.1|10\.16\.1\.128)\b\s.*?\s\bRECEIVE\b'


# ================================= Dashboards =================================

#setup.dashboards.enabled: true
#setup.dashboard.directory: C:\filebeat-8.13.2\kibana

# =================================== Kibana ===================================

setup.kibana:
  host: "https://elk.lab.lan:443"
  username: elastic
  password: password
  ssl.enabled: true

setup.ilm:
  enabled: true
  overwrite: true
  
# ================================== Outputs ===================================

# Configure what output to use when sending the data collected by the beat.

# ---------------------------- Elasticsearch Output ----------------------------
  
#output.elasticsearch:
  #hosts: ["192.168.1.129:9200"]

  #protocol: "http"

  #username: "elastic"
  #password: "password"
  
  

# ------------------------------ Logstash Output -------------------------------

output.logstash:
  # The Logstash hosts
  hosts: ["elk.lab.lan:5044"]

# ================================== Logging ===================================

logging.level: error
logging.to_files: true
logging.files:
  path: C:\filebeat-8.13.2\logs
  name: filebeat
logging.files.rotateeverybytes: 209715200



